name: Docker Build

on:
  push:
    branches: [ main ] # Cambia a tu rama principal si es diferente
  pull_request:
    branches: [ main ] # Cambia a tu rama principal si es diferente
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.emiliogar04 }}
          password: ${{ secrets.TOKENACT3 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.mi-repositorio-devops }}:latest
